[package]
name = "rn"
description = "Utility for displaying the current time using the Misalian Seximal Units with Kunimunean Extensions."
authors = ["Ethan Wu <ethanwu@cs.ucsb.edu>"]
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2"
radix_fmt = "1"
